import React from "react";
import Navbar from "../components/Navbar";
import SectionHome from "../components/SectionHome";

import wellnessImg from "../assets/images/wellness.jpeg";
import therapyImg from "../assets/images/therapy.jpeg";
import productsImg from "../assets/images/products.jpeg";
import communityImg from "../assets/images/community.jpeg";
import aiImg from "../assets/images/ai-recommendation.jpeg";

export default function Home() {
  return (
    <div className="min-h-screen bg-[#EFECE3] dark:bg-[#0A1118] transition-colors duration-700 relative">

      {/* Global Background UI Elements */}
      <div className="fixed inset-0 pointer-events-none opacity-[0.03] dark:opacity-10">
        <div className="absolute inset-0 bg-repeat" style={{ backgroundImage: "url('https://www.transparenttextures.com/patterns/cubes.png')", backgroundSize: '100px' }} />
      </div>

      <Navbar />

      <div className="pt-16 relative z-10">
        <SectionHome
          isFirst
          title="VITA HUB 🌿"
          description="A holistic neural network designed to connect your physiology with trusted therapy practitioners, premium wellness products, and a supportive collective."
          buttonText="Enter System"
          redirectTo="/home"
          image={wellnessImg}
          bgColor="bg-white/40 dark:bg-white/[0.02]"
        />

        <SectionHome
          title="Neural Therapy 🩺"
          description="Sync with verified practitioners and optimize your mental pathways through personalized therapy sessions."
          buttonText="Begin Session"
          redirectTo="/bookTherapy"
          image={therapyImg}
          reverse
        />

        <SectionHome
          title="Bio Products 🛍"
          description="Curated biological enhancements and wellness tools for a higher-performance lifestyle."
          buttonText="Access Shop"
          redirectTo="/products"
          bgColor="bg-[#1B3C53]/5 dark:bg-black/20"
        />

        <SectionHome
          title="The Collective 👥"
          description="Sync your experiences and evolve within a global community of wellness seekers."
          buttonText="Join Node"
          redirectTo="/community"
          image={communityImg}
          reverse
        />

        <SectionHome
          title="AI Diagnostics 🤖"
          description="Personalized wellness pathways generated by our proprietary recommendation engine."
          buttonText="Run Diagnostic"
          redirectTo="/ai-recommendation"
          bgColor="bg-[#FF004D]/5 dark:bg-[#FF004D]/5"
        />
      </div>
    </div>
  );
}